# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20171107_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggroup',
            name='stoped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nosebleedcondition',
            name='notes',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='notes',
            field=models.CharField(max_length=256),
        ),
    ]
