# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20171107_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
