# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20171107_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggroup',
            name='stoped',
        ),
    ]
