# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_remove_loggroup_stoped'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosebleedcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosebleedcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
