# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20171113_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='parameters',
            field=models.ManyToManyField(to='log.ParameterType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='log.Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='log.Type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='log.Person'),
        ),
        migrations.AlterField(
            model_name='note',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='log.Event'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='log.Event'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='log.ParameterType'),
        ),
    ]
