# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20171114_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
