# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='log.Person'),
            preserve_default=False,
        ),
    ]
