# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20171115_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='person',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='log.Type'),
            preserve_default=False,
        ),
    ]
